name: Rebuild python virtual env

on:
  create:
    tags:
      - v*
  push:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1

      - name: install requirements
        run: sudo apt-get install libxmlsec1-dev
        
      - name: Create env
        run: make venv

      - name: Create archive
        run: tar -czf inge6_venv_${{ env.RELEASE_VERSION }}.tar.gz .venv

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: inge6_venv_${{ env.RELEASE_VERSION }}
          path: inge6_venv_${{ env.RELEASE_VERSION }}.tar.gz
