name: Create release package

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: list files
        run: ls -alR

      - name: Create tar
        run: tar -czf inge6_${{ env.RELEASE_VERSION }}.tar.gz ./inge6 ./saml ./static ./*.sh

      - name: Upload release tar
        uses: actions/upload-artifact@v1
        with:
          name: inge6_${{ env.RELEASE_VERSION }}
          path: inge6_${{ env.RELEASE_VERSION }}.tar.gz
