# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  code-quality:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxmlsec1-dev pkg-config
          python -m pip install --upgrade pip setuptools wheel
          make venv

      - name: Check linting (black)
        run: make check

      - name: Test
        run: make test

      - name: Audit
        run: make audit

  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:redislabs/redis
          sudo apt-get update
          sudo apt-get install libxmlsec1-dev pkg-config redis-server
          python -m pip install --upgrade pip setuptools wheel
          make venv

      - name: Setup settings and secrets
        run: make setup

      - name: Test with unittest
        run: make test
