name: Build RDO Python virtual env

on:
  push:
    branches: [ build-venv ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Configure git
        run: git config --global url."https://${{ secrets.REPO_READ_ONLY_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: install requirements
        run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

      - name: prep
        run: sudo mkdir -p /var/www/html

      - name: chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: Copy files
        run: cp -r * /var/www/html

      - name: Create env
        run: cd /var/www/html; make venv

      - name: Create archive
        run: cd /var/www/html; tar -czf /home/runner/work/nl-rdo-max-private/nl-rdo-max-private/max_venv_${{ env.RELEASE_VERSION }}.tar.gz .venv
      - name: Upload venv tar
        uses: actions/upload-artifact@v4
        with:
          name: max_venv_${{ env.RELEASE_VERSION }}
          path: max_venv_${{ env.RELEASE_VERSION }}.tar.gz
